usr/bin/*
usr/lib/libqlcui*
usr/lib/libqlcengine*
usr/share/qlc/documents/*
usr/share/applications/*
usr/share/pixmaps/*
usr/share/qlc/fixtures/*
usr/share/qlc/inputprofiles/*
usr/share/qlc/translations/*
usr/share/mime/packages/qlc.xml

# Input plugins
usr/lib/qt4/plugins/qlc/input/libewinginput.so
usr/lib/qt4/plugins/qlc/input/libhidinput.so
usr/lib/qt4/plugins/qlc/input/libmidiinput.so

# Output plugins
usr/lib/qt4/plugins/qlc/output/libdmx4linuxout.so
usr/lib/qt4/plugins/qlc/output/libmidiout.so
usr/lib/qt4/plugins/qlc/output/libenttecdmxusbout.so
usr/lib/qt4/plugins/qlc/output/libpeperoniout.so
usr/lib/qt4/plugins/qlc/output/libudmxout.so

# UDev rules
etc/udev/rules.d/z65-enttec-dmxusb.rules
etc/udev/rules.d/z65-peperoni.rules
etc/udev/rules.d/z65-anyma-udmx.rules
