.\"                                      Hey, EMACS: -*- nroff -*-
.\" We want the .URL macro
.mso www.tmac
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FACTER SECTION "December 25, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
facter \- Collect and display facts about the system
.SH SYNOPSIS
.B facter
.RI [ options ]
.RI [ fact ]
.RI ...
.SH DESCRIPTION
.B facter
collects and displays facts about the current system.
.PP
The library behind
.B facter
is easy to expand, making
.B facter
an easy way to collect information about a system from within the
shell or within Ruby.
.PP
If no facts are specifically asked for, then all facts will be
returned.

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.
.TP
.B \-\-puppet
Load the Puppet libraries, thus allowing Facter to load Puppet-specific facts.
.TP
.B \-\-debug
Enable debugging.
.TP
.B \-\-yaml
Emit facts in YAML format.

.SH EXAMPLES
.BI facter
Display a list of all facts
.TP
.BI facter \ kernel
Display the
.I kernel
fact
.SH SEE ALSO
.BR puppetd (8),
.BR puppetmasterd (8),
.br
.URL http://reductivelabs.com/products/facter/ "The facter homepage"
.SH BUGS
.URL http://projects.reductivelabs.com/issues/1365 "Reductivelabs issue 1365"
.br
facter can display a single fact only if that fact is generated by a
file with the same name as the fact.  The
.I kernel
fact resides in the
.I kernel.rb
file, and will work, but the facts
.I lsbdistcodename,
.I lsbdistid,
.I lsbdistrelease,
reside in the
.I lsb.rb
file, and will therefore not work as single facts.
.SH AUTHOR
facter was written by Luke Kanies
.PP
This manual page was written by Stig Sandbeck Mathisen <ssm@debian.org>,
for the Debian project (and may be used by others).
